name: paygo_sdk
description: Conjunto de ferramentas que Compõem o SDK de integração com o aplicativo PayGO Integrado via URI.
version: 0.0.6
homepage: https://claudneysessa.github.io/

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: br.com.claudneysessa.paygo_sdk
        pluginClass: PaygoSdkPlugin